services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: |
      apt-get update -y && 
      apt-get install -y chromium && 
      npm install &&
      npm run build
    startCommand: npm start
    envVars:
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
