services:
  - type: web
    name: myauto-scraper
    env: node
    buildCommand: npm ci
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_EXECUTABLE_PATH  # Updated this value
        value: /usr/bin/chromium
    build:
      commands:
        - apt-get update
        - apt-get install -y chromium chromium-driver fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1
        - mkdir -p /opt/render/.cache/puppeteer
        - npm ci
    env:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer